-- Create the exec_sql function to execute SQL statements
-- THIS SHOULD BE CREATED MANUALLY IN THE SUPABASE SQL EDITOR
-- THIS REQUIRES pgAdmin OR ADMIN ACCESS TO SUPABASE
-- USE WITH CAUTION AS IT ALLOWS EXECUTING ANY SQL

CREATE OR REPLACE FUNCTION exec_sql(sql text)
RETURNS void AS $$
BEGIN
  EXECUTE sql;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER; 